name: hashgen_ai
description: >
  HashGen AI is a Flutter package that leverages OpenAI's API to generate relevant hashtags based on the provided content. This package simplifies the process of adding impactful hashtags to your content, enhancing its discoverability.

version: 1.0.1
homepage: https://github.com/Kurubaran-CodeSpace/HashGen-AI
repository: https://github.com/Kurubaran-CodeSpace/HashGen-AI
issue_tracker: https://github.com/Kurubaran-CodeSpace/HashGen-AI/issues

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.0.16
